
from __future__ import annotations

import time
from pathlib import Path
from loguru import logger

from robosmith.config import RunState, TaskSpec
from robosmith.stages.evaluation import EvalReport
from robosmith.agent.models.reward_agent import RewardCandidate

def write_reward_file(
    path: Path,
    candidate: RewardCandidate,
    task_spec: TaskSpec,
) -> None:
    """Write the reward function as a standalone, documented Python file."""
    header = f'''"""
Reward function generated by RoboSmith.

Task: {task_spec.task_description}
Robot: {task_spec.robot_type.value} ({task_spec.robot_model or "auto"})
Environment: {task_spec.environment_id or "auto"}
Generation: {candidate.generation}
Score: {candidate.score}

Usage:
    import numpy as np
    from reward_function import compute_reward

    obs = env.reset()
    action = policy(obs)
    next_obs, _, _, _, info = env.step(action)
    reward, components = compute_reward(obs, action, next_obs, info)
"""

import numpy as np

'''
    path.write_text(header + candidate.code + "\n")

def write_report_card(
    path: Path,
    state: RunState,
    reward_candidate: RewardCandidate | None,
    eval_report: EvalReport | None,
    training_result: object | None,
) -> None:
    """Generate a human-readable markdown report card."""
    spec = state.task_spec
    lines: list[str] = []

    lines.append(f"# RoboSmith report: {spec.task_description}")
    lines.append("")
    lines.append(f"**Run ID:** `{state.run_id}`")
    lines.append(f"**Date:** {time.strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Iterations:** {state.iteration}")
    lines.append("")

    # Task summary
    lines.append("## Task")
    lines.append("")
    lines.append(f"- **Description:** {spec.task_description}")
    lines.append(f"- **Robot:** {spec.robot_type.value} ({spec.robot_model or 'auto'})")
    lines.append(f"- **Environment:** {spec.environment_id or 'auto'}")
    lines.append(f"- **Algorithm:** {spec.algorithm.value}")
    lines.append("")

    # Evaluation results
    if eval_report:
        lines.append("## Evaluation results")
        lines.append("")
        lines.append(f"- **Success rate:** {eval_report.success_rate:.0%}")
        lines.append(f"- **Mean reward:** {eval_report.mean_reward:.2f} (±{eval_report.std_reward:.2f})")
        lines.append(f"- **Best reward:** {eval_report.best_reward:.2f}")
        lines.append(f"- **Worst reward:** {eval_report.worst_reward:.2f}")
        lines.append(f"- **Mean episode length:** {eval_report.mean_episode_length:.0f}")
        lines.append(f"- **Episodes evaluated:** {len(eval_report.episodes)}")
        lines.append(f"- **Decision:** {eval_report.decision.value} — {eval_report.decision_reason}")
        lines.append("")

        if eval_report.criteria_results:
            lines.append("### Success criteria")
            lines.append("")
            for criterion, result in eval_report.criteria_results.items():
                status = "PASS" if result["passed"] else "FAIL"
                value = result.get("value", "N/A")
                lines.append(f"- `{criterion}` → {value} [{status}]")
            lines.append("")

    # Training info
    if training_result and hasattr(training_result, "algorithm"):
        lines.append("## Training")
        lines.append("")
        lines.append(f"- **Algorithm:** {training_result.algorithm}")
        lines.append(f"- **Total timesteps:** {training_result.total_timesteps:,}")
        lines.append(f"- **Training time:** {training_result.training_time_seconds:.1f}s")
        lines.append(f"- **Final mean reward:** {training_result.final_mean_reward:.2f}")
        if training_result.model_path:
            lines.append(f"- **Model checkpoint:** `{training_result.model_path.name}`")
        # Check if video was recorded
        video_path = Path(state.artifacts_dir) / "policy_rollout.mp4" if state.artifacts_dir else None
        if video_path and video_path.exists():
            lines.append(f"- **Policy video:** `policy_rollout.mp4`")
        lines.append("")

    # Reward function
    if reward_candidate:
        lines.append("## Reward function")
        lines.append("")
        lines.append(f"- **Generation:** {reward_candidate.generation}")
        lines.append(f"- **Eval score:** {reward_candidate.score}")
        lines.append("")
        lines.append("```python")
        lines.append(reward_candidate.code.strip())
        lines.append("```")
        lines.append("")

    # Pipeline stages
    lines.append("## Pipeline stages")
    lines.append("")
    for name, record in state.stages.items():
        duration = f"{record.duration_seconds:.1f}s" if record.duration_seconds else "—"
        lines.append(f"- **{name}:** {record.status.value} ({duration})")
    lines.append("")

    # Decision history
    if state.decision_history:
        lines.append("## Decision history")
        lines.append("")
        for d in state.decision_history:
            lines.append(f"- Iteration {d.get('iteration', '?')}: "
                         f"{d.get('decision', '?')} — {d.get('reason', '')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [RoboSmith](https://github.com/Shaswat2001/robosmith)*")

    path.write_text("\n".join(lines))

def push_to_hub(repo_id: str, artifacts_dir: Path) -> tuple[bool, str | None]:
    """Push artifacts to HuggingFace Hub."""
    try:
        from huggingface_hub import HfApi
    except ImportError:
        logger.warning("huggingface-hub not installed — skipping push")
        return False, None

    try:
        api = HfApi()
        api.create_repo(repo_id, exist_ok=True)
        api.upload_folder(
            folder_path=str(artifacts_dir),
            repo_id=repo_id,
            commit_message="RoboSmith run artifacts",
        )
        url = f"https://huggingface.co/{repo_id}"
        logger.info(f"Pushed to HuggingFace Hub → {url}")
        return True, url
    except Exception as e:
        logger.warning(f"Failed to push to Hub: {e}")
        return False, None